language: cpp

matrix:
  include:
    - os: linux
      dist: xenial

git:
  submodules: true

script:
  - cd "$TRAVIS_BUILD_DIR"
  - ./autogen.sh
  - mkdir build && cd build
  - ../configure
  - make -j 4
