name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          ubuntu-20.04
        ]
        include:
          - name: ubuntu-20.04
            os: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install
      run: |
        sudo apt install autoconf libtool libz-dev libfreeimage-dev pkg-config

    - name: Build
      run: |
        ./autogen.sh
        mkdir build
        cd build
        ../configure
        make
